version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mezink_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./docs/sql:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:password@tcp(mysql:3306)/mezink_db",
      "up"
    ]
    depends_on:
      mysql:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mezink_db
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  mysql_data:
